### ISSUE TITLE
 npy file

### ISSUE THREAD

**Issue by zyiyid** [jiaweihe1996/GMTracker#19]
I see that you provided the npy file, what detector got the detection in it?

**Comment by jiaweihe1996** [comment]
Hi. We use public detections (DPM, SDP, FasterRCNN), which are provided by MOT17 dataset. Instead of the original public detections, we use the detections refined with Tracktor and Centertrack. Please refer to [Tracktor](https://arxiv.org/abs/1903.05625), [MPNTrack](https://arxiv.org/abs/1912.07515), [LifT](https://arxiv.org/abs/2006.14550), and [CenterTrack](https://arxiv.org/abs/2004.01177) for more information.
